//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostcodeEverywhere
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.afd.co.uk/", ConfigurationName="PostcodeEverywhere.PostcodeEverywhereSoap")]
    public interface PostcodeEverywhereSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/AddressList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressListAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strCountyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/AddressLookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.Address> AddressLookupAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/AddressLookupRaw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.AddressRaw> AddressLookupRawAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/AddressFastFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressFastFindAsync(string strSerialNumber, string strPassword, string strUserID, string strFastFind, string strCountyType, string strSkip, string strMaxQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/AddressSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressSearchAsync(string strSerialNumber, string strPassword, string strUserID, string strOrganisation, string strProperty, string strStreet, string strLocality, string strTown, string strPostcodeFrom, string strPostcodeTo, string strCounty, string strCountyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/BankLookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.Bank> BankLookupAsync(string strSerialNumber, string strPassword, string strUserID, string strRecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/BankFastFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.BankResultsList> BankFastFindAsync(string strSerialNumber, string strPassword, string strUserID, string strFastFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/BankSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.BankResultsList> BankSearchAsync(string strSerialNumber, string strPassword, string strUserID, string strsortcode, string strpostcode, string strbank, string strbranch, string strphone, string strTown, string strbankBIC, string strbranchBIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/BankCardValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.BankValCard> BankCardValidateAsync(string strSerialNumber, string strPassword, string strUserID, string strCardNumber, string strExpiryMonth, string strExpiryYear, string strIssuenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.afd.co.uk/BankAccountValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PostcodeEverywhere.BankValAccount> BankAccountValidateAsync(string strSerialNumber, string strPassword, string strUserID, string strSortcode, string strAccountNumber);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class AddressResultsList
    {
        
        private int intTotalRecordsFoundField;
        
        private string[] lstAddressesField;
        
        private string[] lstPostkeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int intTotalRecordsFound
        {
            get
            {
                return this.intTotalRecordsFoundField;
            }
            set
            {
                this.intTotalRecordsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] lstAddresses
        {
            get
            {
                return this.lstAddressesField;
            }
            set
            {
                this.lstAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] lstPostkeys
        {
            get
            {
                return this.lstPostkeysField;
            }
            set
            {
                this.lstPostkeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class BankValAccount
    {
        
        private string bankAccountValidateField;
        
        private string bankAccountResultField;
        
        private string bankSortCodeField;
        
        private string bankAccountNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BankAccountValidate
        {
            get
            {
                return this.bankAccountValidateField;
            }
            set
            {
                this.bankAccountValidateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BankAccountResult
        {
            get
            {
                return this.bankAccountResultField;
            }
            set
            {
                this.bankAccountResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankSortCode
        {
            get
            {
                return this.bankSortCodeField;
            }
            set
            {
                this.bankSortCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BankAccountNo
        {
            get
            {
                return this.bankAccountNoField;
            }
            set
            {
                this.bankAccountNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class BankValCard
    {
        
        private string bankCardResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BankCardResult
        {
            get
            {
                return this.bankCardResultField;
            }
            set
            {
                this.bankCardResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class BankResultsList
    {
        
        private object intTotalBankRecordsFoundField;
        
        private string[] lstBankAddressesField;
        
        private string[] lstBankRecordNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object intTotalBankRecordsFound
        {
            get
            {
                return this.intTotalBankRecordsFoundField;
            }
            set
            {
                this.intTotalBankRecordsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] lstBankAddresses
        {
            get
            {
                return this.lstBankAddressesField;
            }
            set
            {
                this.lstBankAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] lstBankRecordNumber
        {
            get
            {
                return this.lstBankRecordNumberField;
            }
            set
            {
                this.lstBankRecordNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class Bank
    {
        
        private string strStatusField;
        
        private string strSortCodeField;
        
        private string strSubBranchSuffixField;
        
        private string strBankBICField;
        
        private string strBranchBICField;
        
        private string strBranchNameField;
        
        private string strBranchTitleField;
        
        private string strMinorLocationNameField;
        
        private string strMajorLocationNameField;
        
        private string strOwnerBankCodeField;
        
        private string strBankNameField;
        
        private string strCentralBankCountryCodeField;
        
        private string strSupervisoryBodyField;
        
        private string strBranchTypeField;
        
        private string strBankOrganisationField;
        
        private string strMainBranchField;
        
        private string strBankPropertyField;
        
        private string strBankStreetField;
        
        private string strBankLocalityField;
        
        private string strBankTownField;
        
        private string strBankCountyField;
        
        private string strBankPostcodeField;
        
        private string strBankLabelField;
        
        private string strBankSTDField;
        
        private string strBankPhoneField;
        
        private string strDeletedDateField;
        
        private string strBACSStatusField;
        
        private string strBACSLastChangeField;
        
        private string strBACSClosedClearingField;
        
        private string strBACSRedirectedFromField;
        
        private string strBACSRedirectToField;
        
        private string strBACSHandlingBankCodeField;
        
        private string strBACSHandlingBankNameField;
        
        private string strBACSHandlingBankStreamField;
        
        private string strBACSSettlementBankCodeField;
        
        private string strBACSSettlementBankNameField;
        
        private string strBACSSettlementSectionField;
        
        private string strBACSSettlementSubSectionField;
        
        private string strBACSAllowedDirectDebitsField;
        
        private string strBACSAllowedBankGiroCreditsField;
        
        private string strBACSAllowedBuildingSocietyCreditsField;
        
        private string strBACSAllowedDividendInterestPaymentsField;
        
        private string strBACSAllowedUnpaidChequeClaimsField;
        
        private string strDDIVoucherFlagField;
        
        private string strAccountNumberedFlagField;
        
        private string strCHAPSPStatusStringField;
        
        private string strCHAPSPLastChangeField;
        
        private string strCHAPSPClosedClearingField;
        
        private string strCHAPSPSettlementBankCodeField;
        
        private string strCHAPSPSettlementBankNameField;
        
        private string strCHAPSEStatusStringField;
        
        private string strCHAPSELastChangeField;
        
        private string strCHAPSEReturnIndicatorField;
        
        private string strCHAPSEEuroRoutingBICBankField;
        
        private string strCHAPSEEuroRoutingBICBranchField;
        
        private string strCHAPSESettlementBankNameField;
        
        private string strCHAPSESettlementBankCodeField;
        
        private string strCCCCStatusStringField;
        
        private string strCCCCLastChangeField;
        
        private string strCCCCReturnIndicatorField;
        
        private string strCCCCClosedClearingField;
        
        private string strCCCCSettlementBankCodeField;
        
        private string strCCCCSettlementBankNameField;
        
        private string strCCCCDebitAgencySortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strStatus
        {
            get
            {
                return this.strStatusField;
            }
            set
            {
                this.strStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strSortCode
        {
            get
            {
                return this.strSortCodeField;
            }
            set
            {
                this.strSortCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strSubBranchSuffix
        {
            get
            {
                return this.strSubBranchSuffixField;
            }
            set
            {
                this.strSubBranchSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string strBankBIC
        {
            get
            {
                return this.strBankBICField;
            }
            set
            {
                this.strBankBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string strBranchBIC
        {
            get
            {
                return this.strBranchBICField;
            }
            set
            {
                this.strBranchBICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string strBranchName
        {
            get
            {
                return this.strBranchNameField;
            }
            set
            {
                this.strBranchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string strBranchTitle
        {
            get
            {
                return this.strBranchTitleField;
            }
            set
            {
                this.strBranchTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string strMinorLocationName
        {
            get
            {
                return this.strMinorLocationNameField;
            }
            set
            {
                this.strMinorLocationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string strMajorLocationName
        {
            get
            {
                return this.strMajorLocationNameField;
            }
            set
            {
                this.strMajorLocationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string strOwnerBankCode
        {
            get
            {
                return this.strOwnerBankCodeField;
            }
            set
            {
                this.strOwnerBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string strBankName
        {
            get
            {
                return this.strBankNameField;
            }
            set
            {
                this.strBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string strCentralBankCountryCode
        {
            get
            {
                return this.strCentralBankCountryCodeField;
            }
            set
            {
                this.strCentralBankCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string strSupervisoryBody
        {
            get
            {
                return this.strSupervisoryBodyField;
            }
            set
            {
                this.strSupervisoryBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string strBranchType
        {
            get
            {
                return this.strBranchTypeField;
            }
            set
            {
                this.strBranchTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string strBankOrganisation
        {
            get
            {
                return this.strBankOrganisationField;
            }
            set
            {
                this.strBankOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string strMainBranch
        {
            get
            {
                return this.strMainBranchField;
            }
            set
            {
                this.strMainBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string strBankProperty
        {
            get
            {
                return this.strBankPropertyField;
            }
            set
            {
                this.strBankPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string strBankStreet
        {
            get
            {
                return this.strBankStreetField;
            }
            set
            {
                this.strBankStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string strBankLocality
        {
            get
            {
                return this.strBankLocalityField;
            }
            set
            {
                this.strBankLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string strBankTown
        {
            get
            {
                return this.strBankTownField;
            }
            set
            {
                this.strBankTownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string strBankCounty
        {
            get
            {
                return this.strBankCountyField;
            }
            set
            {
                this.strBankCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string strBankPostcode
        {
            get
            {
                return this.strBankPostcodeField;
            }
            set
            {
                this.strBankPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string strBankLabel
        {
            get
            {
                return this.strBankLabelField;
            }
            set
            {
                this.strBankLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string strBankSTD
        {
            get
            {
                return this.strBankSTDField;
            }
            set
            {
                this.strBankSTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string strBankPhone
        {
            get
            {
                return this.strBankPhoneField;
            }
            set
            {
                this.strBankPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string strDeletedDate
        {
            get
            {
                return this.strDeletedDateField;
            }
            set
            {
                this.strDeletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string strBACSStatus
        {
            get
            {
                return this.strBACSStatusField;
            }
            set
            {
                this.strBACSStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string strBACSLastChange
        {
            get
            {
                return this.strBACSLastChangeField;
            }
            set
            {
                this.strBACSLastChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string strBACSClosedClearing
        {
            get
            {
                return this.strBACSClosedClearingField;
            }
            set
            {
                this.strBACSClosedClearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string strBACSRedirectedFrom
        {
            get
            {
                return this.strBACSRedirectedFromField;
            }
            set
            {
                this.strBACSRedirectedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string strBACSRedirectTo
        {
            get
            {
                return this.strBACSRedirectToField;
            }
            set
            {
                this.strBACSRedirectToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string strBACSHandlingBankCode
        {
            get
            {
                return this.strBACSHandlingBankCodeField;
            }
            set
            {
                this.strBACSHandlingBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string strBACSHandlingBankName
        {
            get
            {
                return this.strBACSHandlingBankNameField;
            }
            set
            {
                this.strBACSHandlingBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string strBACSHandlingBankStream
        {
            get
            {
                return this.strBACSHandlingBankStreamField;
            }
            set
            {
                this.strBACSHandlingBankStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string strBACSSettlementBankCode
        {
            get
            {
                return this.strBACSSettlementBankCodeField;
            }
            set
            {
                this.strBACSSettlementBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string strBACSSettlementBankName
        {
            get
            {
                return this.strBACSSettlementBankNameField;
            }
            set
            {
                this.strBACSSettlementBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string strBACSSettlementSection
        {
            get
            {
                return this.strBACSSettlementSectionField;
            }
            set
            {
                this.strBACSSettlementSectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string strBACSSettlementSubSection
        {
            get
            {
                return this.strBACSSettlementSubSectionField;
            }
            set
            {
                this.strBACSSettlementSubSectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string strBACSAllowedDirectDebits
        {
            get
            {
                return this.strBACSAllowedDirectDebitsField;
            }
            set
            {
                this.strBACSAllowedDirectDebitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string strBACSAllowedBankGiroCredits
        {
            get
            {
                return this.strBACSAllowedBankGiroCreditsField;
            }
            set
            {
                this.strBACSAllowedBankGiroCreditsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string strBACSAllowedBuildingSocietyCredits
        {
            get
            {
                return this.strBACSAllowedBuildingSocietyCreditsField;
            }
            set
            {
                this.strBACSAllowedBuildingSocietyCreditsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string strBACSAllowedDividendInterestPayments
        {
            get
            {
                return this.strBACSAllowedDividendInterestPaymentsField;
            }
            set
            {
                this.strBACSAllowedDividendInterestPaymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string strBACSAllowedUnpaidChequeClaims
        {
            get
            {
                return this.strBACSAllowedUnpaidChequeClaimsField;
            }
            set
            {
                this.strBACSAllowedUnpaidChequeClaimsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string strDDIVoucherFlag
        {
            get
            {
                return this.strDDIVoucherFlagField;
            }
            set
            {
                this.strDDIVoucherFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string strAccountNumberedFlag
        {
            get
            {
                return this.strAccountNumberedFlagField;
            }
            set
            {
                this.strAccountNumberedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string strCHAPSPStatusString
        {
            get
            {
                return this.strCHAPSPStatusStringField;
            }
            set
            {
                this.strCHAPSPStatusStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string strCHAPSPLastChange
        {
            get
            {
                return this.strCHAPSPLastChangeField;
            }
            set
            {
                this.strCHAPSPLastChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string strCHAPSPClosedClearing
        {
            get
            {
                return this.strCHAPSPClosedClearingField;
            }
            set
            {
                this.strCHAPSPClosedClearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string strCHAPSPSettlementBankCode
        {
            get
            {
                return this.strCHAPSPSettlementBankCodeField;
            }
            set
            {
                this.strCHAPSPSettlementBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string strCHAPSPSettlementBankName
        {
            get
            {
                return this.strCHAPSPSettlementBankNameField;
            }
            set
            {
                this.strCHAPSPSettlementBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string strCHAPSEStatusString
        {
            get
            {
                return this.strCHAPSEStatusStringField;
            }
            set
            {
                this.strCHAPSEStatusStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string strCHAPSELastChange
        {
            get
            {
                return this.strCHAPSELastChangeField;
            }
            set
            {
                this.strCHAPSELastChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string strCHAPSEReturnIndicator
        {
            get
            {
                return this.strCHAPSEReturnIndicatorField;
            }
            set
            {
                this.strCHAPSEReturnIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string strCHAPSEEuroRoutingBICBank
        {
            get
            {
                return this.strCHAPSEEuroRoutingBICBankField;
            }
            set
            {
                this.strCHAPSEEuroRoutingBICBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string strCHAPSEEuroRoutingBICBranch
        {
            get
            {
                return this.strCHAPSEEuroRoutingBICBranchField;
            }
            set
            {
                this.strCHAPSEEuroRoutingBICBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string strCHAPSESettlementBankName
        {
            get
            {
                return this.strCHAPSESettlementBankNameField;
            }
            set
            {
                this.strCHAPSESettlementBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string strCHAPSESettlementBankCode
        {
            get
            {
                return this.strCHAPSESettlementBankCodeField;
            }
            set
            {
                this.strCHAPSESettlementBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string strCCCCStatusString
        {
            get
            {
                return this.strCCCCStatusStringField;
            }
            set
            {
                this.strCCCCStatusStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string strCCCCLastChange
        {
            get
            {
                return this.strCCCCLastChangeField;
            }
            set
            {
                this.strCCCCLastChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string strCCCCReturnIndicator
        {
            get
            {
                return this.strCCCCReturnIndicatorField;
            }
            set
            {
                this.strCCCCReturnIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string strCCCCClosedClearing
        {
            get
            {
                return this.strCCCCClosedClearingField;
            }
            set
            {
                this.strCCCCClosedClearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string strCCCCSettlementBankCode
        {
            get
            {
                return this.strCCCCSettlementBankCodeField;
            }
            set
            {
                this.strCCCCSettlementBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string strCCCCSettlementBankName
        {
            get
            {
                return this.strCCCCSettlementBankNameField;
            }
            set
            {
                this.strCCCCSettlementBankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string strCCCCDebitAgencySortCode
        {
            get
            {
                return this.strCCCCDebitAgencySortCodeField;
            }
            set
            {
                this.strCCCCDebitAgencySortCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class AddressRaw
    {
        
        private string strOrganisationField;
        
        private string strDepartmentField;
        
        private string strNumberField;
        
        private string strSubBuildingField;
        
        private string strBuildingField;
        
        private string strPOBoxField;
        
        private string strDepStreetField;
        
        private string strStreetField;
        
        private string strDoubleDependantLocalityField;
        
        private string strDependantLocalityField;
        
        private string strTownField;
        
        private string strCountyField;
        
        private string strPostcodeField;
        
        private string strDPSField;
        
        private string strMailsortField;
        
        private string strPostcodeTypeField;
        
        private string strHouseholdCountField;
        
        private string strAuthorityField;
        
        private string strConstituencyField;
        
        private string strTVRegionField;
        
        private string strGridEastField;
        
        private string strGridNorthField;
        
        private string strLatitudeField;
        
        private string strLongitudeField;
        
        private string strSTDCodeField;
        
        private string strWardCodeField;
        
        private string strWardNameField;
        
        private string strNHSCodeField;
        
        private string strNHSNameField;
        
        private string strNHSRegionField;
        
        private string strNHSRegionCodeField;
        
        private string strChangedField;
        
        private string strUDPRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strOrganisation
        {
            get
            {
                return this.strOrganisationField;
            }
            set
            {
                this.strOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strDepartment
        {
            get
            {
                return this.strDepartmentField;
            }
            set
            {
                this.strDepartmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strNumber
        {
            get
            {
                return this.strNumberField;
            }
            set
            {
                this.strNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string strSubBuilding
        {
            get
            {
                return this.strSubBuildingField;
            }
            set
            {
                this.strSubBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string strBuilding
        {
            get
            {
                return this.strBuildingField;
            }
            set
            {
                this.strBuildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string strPOBox
        {
            get
            {
                return this.strPOBoxField;
            }
            set
            {
                this.strPOBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string strDepStreet
        {
            get
            {
                return this.strDepStreetField;
            }
            set
            {
                this.strDepStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string strStreet
        {
            get
            {
                return this.strStreetField;
            }
            set
            {
                this.strStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string strDoubleDependantLocality
        {
            get
            {
                return this.strDoubleDependantLocalityField;
            }
            set
            {
                this.strDoubleDependantLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string strDependantLocality
        {
            get
            {
                return this.strDependantLocalityField;
            }
            set
            {
                this.strDependantLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string strTown
        {
            get
            {
                return this.strTownField;
            }
            set
            {
                this.strTownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string strCounty
        {
            get
            {
                return this.strCountyField;
            }
            set
            {
                this.strCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string strPostcode
        {
            get
            {
                return this.strPostcodeField;
            }
            set
            {
                this.strPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string strDPS
        {
            get
            {
                return this.strDPSField;
            }
            set
            {
                this.strDPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string strMailsort
        {
            get
            {
                return this.strMailsortField;
            }
            set
            {
                this.strMailsortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string strPostcodeType
        {
            get
            {
                return this.strPostcodeTypeField;
            }
            set
            {
                this.strPostcodeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string strHouseholdCount
        {
            get
            {
                return this.strHouseholdCountField;
            }
            set
            {
                this.strHouseholdCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string strAuthority
        {
            get
            {
                return this.strAuthorityField;
            }
            set
            {
                this.strAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string strConstituency
        {
            get
            {
                return this.strConstituencyField;
            }
            set
            {
                this.strConstituencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string strTVRegion
        {
            get
            {
                return this.strTVRegionField;
            }
            set
            {
                this.strTVRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string strGridEast
        {
            get
            {
                return this.strGridEastField;
            }
            set
            {
                this.strGridEastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string strGridNorth
        {
            get
            {
                return this.strGridNorthField;
            }
            set
            {
                this.strGridNorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string strLatitude
        {
            get
            {
                return this.strLatitudeField;
            }
            set
            {
                this.strLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string strLongitude
        {
            get
            {
                return this.strLongitudeField;
            }
            set
            {
                this.strLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string strSTDCode
        {
            get
            {
                return this.strSTDCodeField;
            }
            set
            {
                this.strSTDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string strWardCode
        {
            get
            {
                return this.strWardCodeField;
            }
            set
            {
                this.strWardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string strWardName
        {
            get
            {
                return this.strWardNameField;
            }
            set
            {
                this.strWardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string strNHSCode
        {
            get
            {
                return this.strNHSCodeField;
            }
            set
            {
                this.strNHSCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string strNHSName
        {
            get
            {
                return this.strNHSNameField;
            }
            set
            {
                this.strNHSNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string strNHSRegion
        {
            get
            {
                return this.strNHSRegionField;
            }
            set
            {
                this.strNHSRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string strNHSRegionCode
        {
            get
            {
                return this.strNHSRegionCodeField;
            }
            set
            {
                this.strNHSRegionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string strChanged
        {
            get
            {
                return this.strChangedField;
            }
            set
            {
                this.strChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string strUDPRN
        {
            get
            {
                return this.strUDPRNField;
            }
            set
            {
                this.strUDPRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.afd.co.uk/")]
    public partial class Address
    {
        
        private string strOrganisationField;
        
        private string strPropertyField;
        
        private string strStreetField;
        
        private string strLocalityField;
        
        private string strTownField;
        
        private string strCountyField;
        
        private string strPostcodeField;
        
        private string strDPSField;
        
        private string strMailsortField;
        
        private string strPostcodeTypeField;
        
        private string strHouseholdCountField;
        
        private string strAuthorityField;
        
        private string strAuthorityCodeField;
        
        private string strConstituencyField;
        
        private string strTVRegionField;
        
        private string strGridEastField;
        
        private string strGridNorthField;
        
        private string strLatitudeField;
        
        private string strLongitudeField;
        
        private string strSTDCodeField;
        
        private string strWardCodeField;
        
        private string strWardNameField;
        
        private string strNHSCodeField;
        
        private string strNHSNameField;
        
        private string strNHSRegionField;
        
        private string strNHSRegionCodeField;
        
        private string strChangedField;
        
        private string strCensusCodeField;
        
        private string strAffluenceField;
        
        private string strLifeStageField;
        
        private string strAdditionalCensusInfoField;
        
        private string strOccupancyField;
        
        private string strOccupancyDescriptionField;
        
        private string strAddressTypeField;
        
        private string strAddressTypeDescriptionField;
        
        private string strPCTCodeField;
        
        private string strPCTNameField;
        
        private string strEERCodeField;
        
        private string strEERNameField;
        
        private string strUrbanRuralCodeField;
        
        private string strUrbanRuralNameField;
        
        private string strLEACodeField;
        
        private string strLEANameField;
        
        private string strUDPRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strOrganisation
        {
            get
            {
                return this.strOrganisationField;
            }
            set
            {
                this.strOrganisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strProperty
        {
            get
            {
                return this.strPropertyField;
            }
            set
            {
                this.strPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strStreet
        {
            get
            {
                return this.strStreetField;
            }
            set
            {
                this.strStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string strLocality
        {
            get
            {
                return this.strLocalityField;
            }
            set
            {
                this.strLocalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string strTown
        {
            get
            {
                return this.strTownField;
            }
            set
            {
                this.strTownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string strCounty
        {
            get
            {
                return this.strCountyField;
            }
            set
            {
                this.strCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string strPostcode
        {
            get
            {
                return this.strPostcodeField;
            }
            set
            {
                this.strPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string strDPS
        {
            get
            {
                return this.strDPSField;
            }
            set
            {
                this.strDPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string strMailsort
        {
            get
            {
                return this.strMailsortField;
            }
            set
            {
                this.strMailsortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string strPostcodeType
        {
            get
            {
                return this.strPostcodeTypeField;
            }
            set
            {
                this.strPostcodeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string strHouseholdCount
        {
            get
            {
                return this.strHouseholdCountField;
            }
            set
            {
                this.strHouseholdCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string strAuthority
        {
            get
            {
                return this.strAuthorityField;
            }
            set
            {
                this.strAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string strAuthorityCode
        {
            get
            {
                return this.strAuthorityCodeField;
            }
            set
            {
                this.strAuthorityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string strConstituency
        {
            get
            {
                return this.strConstituencyField;
            }
            set
            {
                this.strConstituencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string strTVRegion
        {
            get
            {
                return this.strTVRegionField;
            }
            set
            {
                this.strTVRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string strGridEast
        {
            get
            {
                return this.strGridEastField;
            }
            set
            {
                this.strGridEastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string strGridNorth
        {
            get
            {
                return this.strGridNorthField;
            }
            set
            {
                this.strGridNorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string strLatitude
        {
            get
            {
                return this.strLatitudeField;
            }
            set
            {
                this.strLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string strLongitude
        {
            get
            {
                return this.strLongitudeField;
            }
            set
            {
                this.strLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string strSTDCode
        {
            get
            {
                return this.strSTDCodeField;
            }
            set
            {
                this.strSTDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string strWardCode
        {
            get
            {
                return this.strWardCodeField;
            }
            set
            {
                this.strWardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string strWardName
        {
            get
            {
                return this.strWardNameField;
            }
            set
            {
                this.strWardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string strNHSCode
        {
            get
            {
                return this.strNHSCodeField;
            }
            set
            {
                this.strNHSCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string strNHSName
        {
            get
            {
                return this.strNHSNameField;
            }
            set
            {
                this.strNHSNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string strNHSRegion
        {
            get
            {
                return this.strNHSRegionField;
            }
            set
            {
                this.strNHSRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string strNHSRegionCode
        {
            get
            {
                return this.strNHSRegionCodeField;
            }
            set
            {
                this.strNHSRegionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string strChanged
        {
            get
            {
                return this.strChangedField;
            }
            set
            {
                this.strChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string strCensusCode
        {
            get
            {
                return this.strCensusCodeField;
            }
            set
            {
                this.strCensusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string strAffluence
        {
            get
            {
                return this.strAffluenceField;
            }
            set
            {
                this.strAffluenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string strLifeStage
        {
            get
            {
                return this.strLifeStageField;
            }
            set
            {
                this.strLifeStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string strAdditionalCensusInfo
        {
            get
            {
                return this.strAdditionalCensusInfoField;
            }
            set
            {
                this.strAdditionalCensusInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string strOccupancy
        {
            get
            {
                return this.strOccupancyField;
            }
            set
            {
                this.strOccupancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string strOccupancyDescription
        {
            get
            {
                return this.strOccupancyDescriptionField;
            }
            set
            {
                this.strOccupancyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string strAddressType
        {
            get
            {
                return this.strAddressTypeField;
            }
            set
            {
                this.strAddressTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string strAddressTypeDescription
        {
            get
            {
                return this.strAddressTypeDescriptionField;
            }
            set
            {
                this.strAddressTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string strPCTCode
        {
            get
            {
                return this.strPCTCodeField;
            }
            set
            {
                this.strPCTCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string strPCTName
        {
            get
            {
                return this.strPCTNameField;
            }
            set
            {
                this.strPCTNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string strEERCode
        {
            get
            {
                return this.strEERCodeField;
            }
            set
            {
                this.strEERCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string strEERName
        {
            get
            {
                return this.strEERNameField;
            }
            set
            {
                this.strEERNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string strUrbanRuralCode
        {
            get
            {
                return this.strUrbanRuralCodeField;
            }
            set
            {
                this.strUrbanRuralCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string strUrbanRuralName
        {
            get
            {
                return this.strUrbanRuralNameField;
            }
            set
            {
                this.strUrbanRuralNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string strLEACode
        {
            get
            {
                return this.strLEACodeField;
            }
            set
            {
                this.strLEACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string strLEAName
        {
            get
            {
                return this.strLEANameField;
            }
            set
            {
                this.strLEANameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string strUDPRN
        {
            get
            {
                return this.strUDPRNField;
            }
            set
            {
                this.strUDPRNField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface PostcodeEverywhereSoapChannel : PostcodeEverywhere.PostcodeEverywhereSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class PostcodeEverywhereSoapClient : System.ServiceModel.ClientBase<PostcodeEverywhere.PostcodeEverywhereSoap>, PostcodeEverywhere.PostcodeEverywhereSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PostcodeEverywhereSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PostcodeEverywhereSoapClient.GetBindingForEndpoint(endpointConfiguration), PostcodeEverywhereSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostcodeEverywhereSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PostcodeEverywhereSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostcodeEverywhereSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PostcodeEverywhereSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostcodeEverywhereSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressListAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strCountyType)
        {
            return base.Channel.AddressListAsync(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strCountyType);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.Address> AddressLookupAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType)
        {
            return base.Channel.AddressLookupAsync(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strPostkey, strCountyType);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.AddressRaw> AddressLookupRawAsync(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType)
        {
            return base.Channel.AddressLookupRawAsync(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strPostkey, strCountyType);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressFastFindAsync(string strSerialNumber, string strPassword, string strUserID, string strFastFind, string strCountyType, string strSkip, string strMaxQuantity)
        {
            return base.Channel.AddressFastFindAsync(strSerialNumber, strPassword, strUserID, strFastFind, strCountyType, strSkip, strMaxQuantity);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.AddressResultsList> AddressSearchAsync(string strSerialNumber, string strPassword, string strUserID, string strOrganisation, string strProperty, string strStreet, string strLocality, string strTown, string strPostcodeFrom, string strPostcodeTo, string strCounty, string strCountyType)
        {
            return base.Channel.AddressSearchAsync(strSerialNumber, strPassword, strUserID, strOrganisation, strProperty, strStreet, strLocality, strTown, strPostcodeFrom, strPostcodeTo, strCounty, strCountyType);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.Bank> BankLookupAsync(string strSerialNumber, string strPassword, string strUserID, string strRecord)
        {
            return base.Channel.BankLookupAsync(strSerialNumber, strPassword, strUserID, strRecord);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.BankResultsList> BankFastFindAsync(string strSerialNumber, string strPassword, string strUserID, string strFastFind)
        {
            return base.Channel.BankFastFindAsync(strSerialNumber, strPassword, strUserID, strFastFind);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.BankResultsList> BankSearchAsync(string strSerialNumber, string strPassword, string strUserID, string strsortcode, string strpostcode, string strbank, string strbranch, string strphone, string strTown, string strbankBIC, string strbranchBIC)
        {
            return base.Channel.BankSearchAsync(strSerialNumber, strPassword, strUserID, strsortcode, strpostcode, strbank, strbranch, strphone, strTown, strbankBIC, strbranchBIC);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.BankValCard> BankCardValidateAsync(string strSerialNumber, string strPassword, string strUserID, string strCardNumber, string strExpiryMonth, string strExpiryYear, string strIssuenumber)
        {
            return base.Channel.BankCardValidateAsync(strSerialNumber, strPassword, strUserID, strCardNumber, strExpiryMonth, strExpiryYear, strIssuenumber);
        }
        
        public System.Threading.Tasks.Task<PostcodeEverywhere.BankValAccount> BankAccountValidateAsync(string strSerialNumber, string strPassword, string strUserID, string strSortcode, string strAccountNumber)
        {
            return base.Channel.BankAccountValidateAsync(strSerialNumber, strPassword, strUserID, strSortcode, strAccountNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PostcodeEverywhereSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PostcodeEverywhereSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PostcodeEverywhereSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.afd.co.uk/PCE_WebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PostcodeEverywhereSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.afd.co.uk/PCE_WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PostcodeEverywhereSoap,
            
            PostcodeEverywhereSoap12,
        }
    }
}
