//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostcodeEverywhere
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ws.afd.co.uk/", ConfigurationName = "PostcodeEverywhere.PostcodeEverywhereSoap")]
    public interface PostcodeEverywhereSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/AddressList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.AddressResultsList AddressList(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strCountyType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/AddressLookup", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.Address AddressLookup(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/AddressLookupRaw", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.AddressRaw AddressLookupRaw(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/AddressFastFind", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.AddressResultsList AddressFastFind(string strSerialNumber, string strPassword, string strUserID, string strFastFind, string strCountyType, string strSkip, string strMaxQuantity);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/AddressSearch", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.AddressResultsList AddressSearch(string strSerialNumber, string strPassword, string strUserID, string strOrganisation, string strProperty, string strStreet, string strLocality, string strTown, string strPostcodeFrom, string strPostcodeTo, string strCounty, string strCountyType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/BankLookup", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.Bank BankLookup(string strSerialNumber, string strPassword, string strUserID, string strRecord);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/BankFastFind", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.BankResultsList BankFastFind(string strSerialNumber, string strPassword, string strUserID, string strFastFind);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/BankSearch", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.BankResultsList BankSearch(string strSerialNumber, string strPassword, string strUserID, string strsortcode, string strpostcode, string strbank, string strbranch, string strphone, string strTown, string strbankBIC, string strbranchBIC);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/BankCardValidate", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.BankValCard BankCardValidate(string strSerialNumber, string strPassword, string strUserID, string strCardNumber, string strExpiryMonth, string strExpiryYear, string strIssuenumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.afd.co.uk/BankAccountValidate", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostcodeEverywhere.BankValAccount BankAccountValidate(string strSerialNumber, string strPassword, string strUserID, string strSortcode, string strAccountNumber);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class AddressResultsList : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int intTotalRecordsFoundField;

        private string[] lstAddressesField;

        private string[] lstPostkeysField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int intTotalRecordsFound
        {
            get
            {
                return this.intTotalRecordsFoundField;
            }
            set
            {
                this.intTotalRecordsFoundField = value;
                this.RaisePropertyChanged("intTotalRecordsFound");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        public string[] lstAddresses
        {
            get
            {
                return this.lstAddressesField;
            }
            set
            {
                this.lstAddressesField = value;
                this.RaisePropertyChanged("lstAddresses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        public string[] lstPostkeys
        {
            get
            {
                return this.lstPostkeysField;
            }
            set
            {
                this.lstPostkeysField = value;
                this.RaisePropertyChanged("lstPostkeys");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class BankValAccount : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string bankAccountValidateField;

        private string bankAccountResultField;

        private string bankSortCodeField;

        private string bankAccountNoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BankAccountValidate
        {
            get
            {
                return this.bankAccountValidateField;
            }
            set
            {
                this.bankAccountValidateField = value;
                this.RaisePropertyChanged("BankAccountValidate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string BankAccountResult
        {
            get
            {
                return this.bankAccountResultField;
            }
            set
            {
                this.bankAccountResultField = value;
                this.RaisePropertyChanged("BankAccountResult");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string BankSortCode
        {
            get
            {
                return this.bankSortCodeField;
            }
            set
            {
                this.bankSortCodeField = value;
                this.RaisePropertyChanged("BankSortCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string BankAccountNo
        {
            get
            {
                return this.bankAccountNoField;
            }
            set
            {
                this.bankAccountNoField = value;
                this.RaisePropertyChanged("BankAccountNo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class BankValCard : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string bankCardResultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BankCardResult
        {
            get
            {
                return this.bankCardResultField;
            }
            set
            {
                this.bankCardResultField = value;
                this.RaisePropertyChanged("BankCardResult");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class BankResultsList : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object intTotalBankRecordsFoundField;

        private string[] lstBankAddressesField;

        private string[] lstBankRecordNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public object intTotalBankRecordsFound
        {
            get
            {
                return this.intTotalBankRecordsFoundField;
            }
            set
            {
                this.intTotalBankRecordsFoundField = value;
                this.RaisePropertyChanged("intTotalBankRecordsFound");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        public string[] lstBankAddresses
        {
            get
            {
                return this.lstBankAddressesField;
            }
            set
            {
                this.lstBankAddressesField = value;
                this.RaisePropertyChanged("lstBankAddresses");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        public string[] lstBankRecordNumber
        {
            get
            {
                return this.lstBankRecordNumberField;
            }
            set
            {
                this.lstBankRecordNumberField = value;
                this.RaisePropertyChanged("lstBankRecordNumber");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class Bank : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string strStatusField;

        private string strSortCodeField;

        private string strSubBranchSuffixField;

        private string strBankBICField;

        private string strBranchBICField;

        private string strBranchNameField;

        private string strBranchTitleField;

        private string strMinorLocationNameField;

        private string strMajorLocationNameField;

        private string strOwnerBankCodeField;

        private string strBankNameField;

        private string strCentralBankCountryCodeField;

        private string strSupervisoryBodyField;

        private string strBranchTypeField;

        private string strBankOrganisationField;

        private string strMainBranchField;

        private string strBankPropertyField;

        private string strBankStreetField;

        private string strBankLocalityField;

        private string strBankTownField;

        private string strBankCountyField;

        private string strBankPostcodeField;

        private string strBankLabelField;

        private string strBankSTDField;

        private string strBankPhoneField;

        private string strDeletedDateField;

        private string strBACSStatusField;

        private string strBACSLastChangeField;

        private string strBACSClosedClearingField;

        private string strBACSRedirectedFromField;

        private string strBACSRedirectToField;

        private string strBACSHandlingBankCodeField;

        private string strBACSHandlingBankNameField;

        private string strBACSHandlingBankStreamField;

        private string strBACSSettlementBankCodeField;

        private string strBACSSettlementBankNameField;

        private string strBACSSettlementSectionField;

        private string strBACSSettlementSubSectionField;

        private string strBACSAllowedDirectDebitsField;

        private string strBACSAllowedBankGiroCreditsField;

        private string strBACSAllowedBuildingSocietyCreditsField;

        private string strBACSAllowedDividendInterestPaymentsField;

        private string strBACSAllowedUnpaidChequeClaimsField;

        private string strDDIVoucherFlagField;

        private string strAccountNumberedFlagField;

        private string strCHAPSPStatusStringField;

        private string strCHAPSPLastChangeField;

        private string strCHAPSPClosedClearingField;

        private string strCHAPSPSettlementBankCodeField;

        private string strCHAPSPSettlementBankNameField;

        private string strCHAPSEStatusStringField;

        private string strCHAPSELastChangeField;

        private string strCHAPSEReturnIndicatorField;

        private string strCHAPSEEuroRoutingBICBankField;

        private string strCHAPSEEuroRoutingBICBranchField;

        private string strCHAPSESettlementBankNameField;

        private string strCHAPSESettlementBankCodeField;

        private string strCCCCStatusStringField;

        private string strCCCCLastChangeField;

        private string strCCCCReturnIndicatorField;

        private string strCCCCClosedClearingField;

        private string strCCCCSettlementBankCodeField;

        private string strCCCCSettlementBankNameField;

        private string strCCCCDebitAgencySortCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string strStatus
        {
            get
            {
                return this.strStatusField;
            }
            set
            {
                this.strStatusField = value;
                this.RaisePropertyChanged("strStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string strSortCode
        {
            get
            {
                return this.strSortCodeField;
            }
            set
            {
                this.strSortCodeField = value;
                this.RaisePropertyChanged("strSortCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string strSubBranchSuffix
        {
            get
            {
                return this.strSubBranchSuffixField;
            }
            set
            {
                this.strSubBranchSuffixField = value;
                this.RaisePropertyChanged("strSubBranchSuffix");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string strBankBIC
        {
            get
            {
                return this.strBankBICField;
            }
            set
            {
                this.strBankBICField = value;
                this.RaisePropertyChanged("strBankBIC");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string strBranchBIC
        {
            get
            {
                return this.strBranchBICField;
            }
            set
            {
                this.strBranchBICField = value;
                this.RaisePropertyChanged("strBranchBIC");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string strBranchName
        {
            get
            {
                return this.strBranchNameField;
            }
            set
            {
                this.strBranchNameField = value;
                this.RaisePropertyChanged("strBranchName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string strBranchTitle
        {
            get
            {
                return this.strBranchTitleField;
            }
            set
            {
                this.strBranchTitleField = value;
                this.RaisePropertyChanged("strBranchTitle");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string strMinorLocationName
        {
            get
            {
                return this.strMinorLocationNameField;
            }
            set
            {
                this.strMinorLocationNameField = value;
                this.RaisePropertyChanged("strMinorLocationName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string strMajorLocationName
        {
            get
            {
                return this.strMajorLocationNameField;
            }
            set
            {
                this.strMajorLocationNameField = value;
                this.RaisePropertyChanged("strMajorLocationName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string strOwnerBankCode
        {
            get
            {
                return this.strOwnerBankCodeField;
            }
            set
            {
                this.strOwnerBankCodeField = value;
                this.RaisePropertyChanged("strOwnerBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string strBankName
        {
            get
            {
                return this.strBankNameField;
            }
            set
            {
                this.strBankNameField = value;
                this.RaisePropertyChanged("strBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string strCentralBankCountryCode
        {
            get
            {
                return this.strCentralBankCountryCodeField;
            }
            set
            {
                this.strCentralBankCountryCodeField = value;
                this.RaisePropertyChanged("strCentralBankCountryCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string strSupervisoryBody
        {
            get
            {
                return this.strSupervisoryBodyField;
            }
            set
            {
                this.strSupervisoryBodyField = value;
                this.RaisePropertyChanged("strSupervisoryBody");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string strBranchType
        {
            get
            {
                return this.strBranchTypeField;
            }
            set
            {
                this.strBranchTypeField = value;
                this.RaisePropertyChanged("strBranchType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string strBankOrganisation
        {
            get
            {
                return this.strBankOrganisationField;
            }
            set
            {
                this.strBankOrganisationField = value;
                this.RaisePropertyChanged("strBankOrganisation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string strMainBranch
        {
            get
            {
                return this.strMainBranchField;
            }
            set
            {
                this.strMainBranchField = value;
                this.RaisePropertyChanged("strMainBranch");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string strBankProperty
        {
            get
            {
                return this.strBankPropertyField;
            }
            set
            {
                this.strBankPropertyField = value;
                this.RaisePropertyChanged("strBankProperty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string strBankStreet
        {
            get
            {
                return this.strBankStreetField;
            }
            set
            {
                this.strBankStreetField = value;
                this.RaisePropertyChanged("strBankStreet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string strBankLocality
        {
            get
            {
                return this.strBankLocalityField;
            }
            set
            {
                this.strBankLocalityField = value;
                this.RaisePropertyChanged("strBankLocality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string strBankTown
        {
            get
            {
                return this.strBankTownField;
            }
            set
            {
                this.strBankTownField = value;
                this.RaisePropertyChanged("strBankTown");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string strBankCounty
        {
            get
            {
                return this.strBankCountyField;
            }
            set
            {
                this.strBankCountyField = value;
                this.RaisePropertyChanged("strBankCounty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string strBankPostcode
        {
            get
            {
                return this.strBankPostcodeField;
            }
            set
            {
                this.strBankPostcodeField = value;
                this.RaisePropertyChanged("strBankPostcode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string strBankLabel
        {
            get
            {
                return this.strBankLabelField;
            }
            set
            {
                this.strBankLabelField = value;
                this.RaisePropertyChanged("strBankLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string strBankSTD
        {
            get
            {
                return this.strBankSTDField;
            }
            set
            {
                this.strBankSTDField = value;
                this.RaisePropertyChanged("strBankSTD");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string strBankPhone
        {
            get
            {
                return this.strBankPhoneField;
            }
            set
            {
                this.strBankPhoneField = value;
                this.RaisePropertyChanged("strBankPhone");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string strDeletedDate
        {
            get
            {
                return this.strDeletedDateField;
            }
            set
            {
                this.strDeletedDateField = value;
                this.RaisePropertyChanged("strDeletedDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string strBACSStatus
        {
            get
            {
                return this.strBACSStatusField;
            }
            set
            {
                this.strBACSStatusField = value;
                this.RaisePropertyChanged("strBACSStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public string strBACSLastChange
        {
            get
            {
                return this.strBACSLastChangeField;
            }
            set
            {
                this.strBACSLastChangeField = value;
                this.RaisePropertyChanged("strBACSLastChange");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public string strBACSClosedClearing
        {
            get
            {
                return this.strBACSClosedClearingField;
            }
            set
            {
                this.strBACSClosedClearingField = value;
                this.RaisePropertyChanged("strBACSClosedClearing");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public string strBACSRedirectedFrom
        {
            get
            {
                return this.strBACSRedirectedFromField;
            }
            set
            {
                this.strBACSRedirectedFromField = value;
                this.RaisePropertyChanged("strBACSRedirectedFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public string strBACSRedirectTo
        {
            get
            {
                return this.strBACSRedirectToField;
            }
            set
            {
                this.strBACSRedirectToField = value;
                this.RaisePropertyChanged("strBACSRedirectTo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 31)]
        public string strBACSHandlingBankCode
        {
            get
            {
                return this.strBACSHandlingBankCodeField;
            }
            set
            {
                this.strBACSHandlingBankCodeField = value;
                this.RaisePropertyChanged("strBACSHandlingBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public string strBACSHandlingBankName
        {
            get
            {
                return this.strBACSHandlingBankNameField;
            }
            set
            {
                this.strBACSHandlingBankNameField = value;
                this.RaisePropertyChanged("strBACSHandlingBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public string strBACSHandlingBankStream
        {
            get
            {
                return this.strBACSHandlingBankStreamField;
            }
            set
            {
                this.strBACSHandlingBankStreamField = value;
                this.RaisePropertyChanged("strBACSHandlingBankStream");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string strBACSSettlementBankCode
        {
            get
            {
                return this.strBACSSettlementBankCodeField;
            }
            set
            {
                this.strBACSSettlementBankCodeField = value;
                this.RaisePropertyChanged("strBACSSettlementBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 35)]
        public string strBACSSettlementBankName
        {
            get
            {
                return this.strBACSSettlementBankNameField;
            }
            set
            {
                this.strBACSSettlementBankNameField = value;
                this.RaisePropertyChanged("strBACSSettlementBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string strBACSSettlementSection
        {
            get
            {
                return this.strBACSSettlementSectionField;
            }
            set
            {
                this.strBACSSettlementSectionField = value;
                this.RaisePropertyChanged("strBACSSettlementSection");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 37)]
        public string strBACSSettlementSubSection
        {
            get
            {
                return this.strBACSSettlementSubSectionField;
            }
            set
            {
                this.strBACSSettlementSubSectionField = value;
                this.RaisePropertyChanged("strBACSSettlementSubSection");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 38)]
        public string strBACSAllowedDirectDebits
        {
            get
            {
                return this.strBACSAllowedDirectDebitsField;
            }
            set
            {
                this.strBACSAllowedDirectDebitsField = value;
                this.RaisePropertyChanged("strBACSAllowedDirectDebits");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 39)]
        public string strBACSAllowedBankGiroCredits
        {
            get
            {
                return this.strBACSAllowedBankGiroCreditsField;
            }
            set
            {
                this.strBACSAllowedBankGiroCreditsField = value;
                this.RaisePropertyChanged("strBACSAllowedBankGiroCredits");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 40)]
        public string strBACSAllowedBuildingSocietyCredits
        {
            get
            {
                return this.strBACSAllowedBuildingSocietyCreditsField;
            }
            set
            {
                this.strBACSAllowedBuildingSocietyCreditsField = value;
                this.RaisePropertyChanged("strBACSAllowedBuildingSocietyCredits");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 41)]
        public string strBACSAllowedDividendInterestPayments
        {
            get
            {
                return this.strBACSAllowedDividendInterestPaymentsField;
            }
            set
            {
                this.strBACSAllowedDividendInterestPaymentsField = value;
                this.RaisePropertyChanged("strBACSAllowedDividendInterestPayments");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 42)]
        public string strBACSAllowedUnpaidChequeClaims
        {
            get
            {
                return this.strBACSAllowedUnpaidChequeClaimsField;
            }
            set
            {
                this.strBACSAllowedUnpaidChequeClaimsField = value;
                this.RaisePropertyChanged("strBACSAllowedUnpaidChequeClaims");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 43)]
        public string strDDIVoucherFlag
        {
            get
            {
                return this.strDDIVoucherFlagField;
            }
            set
            {
                this.strDDIVoucherFlagField = value;
                this.RaisePropertyChanged("strDDIVoucherFlag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 44)]
        public string strAccountNumberedFlag
        {
            get
            {
                return this.strAccountNumberedFlagField;
            }
            set
            {
                this.strAccountNumberedFlagField = value;
                this.RaisePropertyChanged("strAccountNumberedFlag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 45)]
        public string strCHAPSPStatusString
        {
            get
            {
                return this.strCHAPSPStatusStringField;
            }
            set
            {
                this.strCHAPSPStatusStringField = value;
                this.RaisePropertyChanged("strCHAPSPStatusString");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 46)]
        public string strCHAPSPLastChange
        {
            get
            {
                return this.strCHAPSPLastChangeField;
            }
            set
            {
                this.strCHAPSPLastChangeField = value;
                this.RaisePropertyChanged("strCHAPSPLastChange");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 47)]
        public string strCHAPSPClosedClearing
        {
            get
            {
                return this.strCHAPSPClosedClearingField;
            }
            set
            {
                this.strCHAPSPClosedClearingField = value;
                this.RaisePropertyChanged("strCHAPSPClosedClearing");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 48)]
        public string strCHAPSPSettlementBankCode
        {
            get
            {
                return this.strCHAPSPSettlementBankCodeField;
            }
            set
            {
                this.strCHAPSPSettlementBankCodeField = value;
                this.RaisePropertyChanged("strCHAPSPSettlementBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 49)]
        public string strCHAPSPSettlementBankName
        {
            get
            {
                return this.strCHAPSPSettlementBankNameField;
            }
            set
            {
                this.strCHAPSPSettlementBankNameField = value;
                this.RaisePropertyChanged("strCHAPSPSettlementBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 50)]
        public string strCHAPSEStatusString
        {
            get
            {
                return this.strCHAPSEStatusStringField;
            }
            set
            {
                this.strCHAPSEStatusStringField = value;
                this.RaisePropertyChanged("strCHAPSEStatusString");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 51)]
        public string strCHAPSELastChange
        {
            get
            {
                return this.strCHAPSELastChangeField;
            }
            set
            {
                this.strCHAPSELastChangeField = value;
                this.RaisePropertyChanged("strCHAPSELastChange");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 52)]
        public string strCHAPSEReturnIndicator
        {
            get
            {
                return this.strCHAPSEReturnIndicatorField;
            }
            set
            {
                this.strCHAPSEReturnIndicatorField = value;
                this.RaisePropertyChanged("strCHAPSEReturnIndicator");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 53)]
        public string strCHAPSEEuroRoutingBICBank
        {
            get
            {
                return this.strCHAPSEEuroRoutingBICBankField;
            }
            set
            {
                this.strCHAPSEEuroRoutingBICBankField = value;
                this.RaisePropertyChanged("strCHAPSEEuroRoutingBICBank");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 54)]
        public string strCHAPSEEuroRoutingBICBranch
        {
            get
            {
                return this.strCHAPSEEuroRoutingBICBranchField;
            }
            set
            {
                this.strCHAPSEEuroRoutingBICBranchField = value;
                this.RaisePropertyChanged("strCHAPSEEuroRoutingBICBranch");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 55)]
        public string strCHAPSESettlementBankName
        {
            get
            {
                return this.strCHAPSESettlementBankNameField;
            }
            set
            {
                this.strCHAPSESettlementBankNameField = value;
                this.RaisePropertyChanged("strCHAPSESettlementBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 56)]
        public string strCHAPSESettlementBankCode
        {
            get
            {
                return this.strCHAPSESettlementBankCodeField;
            }
            set
            {
                this.strCHAPSESettlementBankCodeField = value;
                this.RaisePropertyChanged("strCHAPSESettlementBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 57)]
        public string strCCCCStatusString
        {
            get
            {
                return this.strCCCCStatusStringField;
            }
            set
            {
                this.strCCCCStatusStringField = value;
                this.RaisePropertyChanged("strCCCCStatusString");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 58)]
        public string strCCCCLastChange
        {
            get
            {
                return this.strCCCCLastChangeField;
            }
            set
            {
                this.strCCCCLastChangeField = value;
                this.RaisePropertyChanged("strCCCCLastChange");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 59)]
        public string strCCCCReturnIndicator
        {
            get
            {
                return this.strCCCCReturnIndicatorField;
            }
            set
            {
                this.strCCCCReturnIndicatorField = value;
                this.RaisePropertyChanged("strCCCCReturnIndicator");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 60)]
        public string strCCCCClosedClearing
        {
            get
            {
                return this.strCCCCClosedClearingField;
            }
            set
            {
                this.strCCCCClosedClearingField = value;
                this.RaisePropertyChanged("strCCCCClosedClearing");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 61)]
        public string strCCCCSettlementBankCode
        {
            get
            {
                return this.strCCCCSettlementBankCodeField;
            }
            set
            {
                this.strCCCCSettlementBankCodeField = value;
                this.RaisePropertyChanged("strCCCCSettlementBankCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 62)]
        public string strCCCCSettlementBankName
        {
            get
            {
                return this.strCCCCSettlementBankNameField;
            }
            set
            {
                this.strCCCCSettlementBankNameField = value;
                this.RaisePropertyChanged("strCCCCSettlementBankName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 63)]
        public string strCCCCDebitAgencySortCode
        {
            get
            {
                return this.strCCCCDebitAgencySortCodeField;
            }
            set
            {
                this.strCCCCDebitAgencySortCodeField = value;
                this.RaisePropertyChanged("strCCCCDebitAgencySortCode");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class AddressRaw : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string strOrganisationField;

        private string strDepartmentField;

        private string strNumberField;

        private string strSubBuildingField;

        private string strBuildingField;

        private string strPOBoxField;

        private string strDepStreetField;

        private string strStreetField;

        private string strDoubleDependantLocalityField;

        private string strDependantLocalityField;

        private string strTownField;

        private string strCountyField;

        private string strPostcodeField;

        private string strDPSField;

        private string strMailsortField;

        private string strPostcodeTypeField;

        private string strHouseholdCountField;

        private string strAuthorityField;

        private string strConstituencyField;

        private string strTVRegionField;

        private string strGridEastField;

        private string strGridNorthField;

        private string strLatitudeField;

        private string strLongitudeField;

        private string strSTDCodeField;

        private string strWardCodeField;

        private string strWardNameField;

        private string strNHSCodeField;

        private string strNHSNameField;

        private string strNHSRegionField;

        private string strNHSRegionCodeField;

        private string strChangedField;

        private string strUDPRNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string strOrganisation
        {
            get
            {
                return this.strOrganisationField;
            }
            set
            {
                this.strOrganisationField = value;
                this.RaisePropertyChanged("strOrganisation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string strDepartment
        {
            get
            {
                return this.strDepartmentField;
            }
            set
            {
                this.strDepartmentField = value;
                this.RaisePropertyChanged("strDepartment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string strNumber
        {
            get
            {
                return this.strNumberField;
            }
            set
            {
                this.strNumberField = value;
                this.RaisePropertyChanged("strNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string strSubBuilding
        {
            get
            {
                return this.strSubBuildingField;
            }
            set
            {
                this.strSubBuildingField = value;
                this.RaisePropertyChanged("strSubBuilding");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string strBuilding
        {
            get
            {
                return this.strBuildingField;
            }
            set
            {
                this.strBuildingField = value;
                this.RaisePropertyChanged("strBuilding");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string strPOBox
        {
            get
            {
                return this.strPOBoxField;
            }
            set
            {
                this.strPOBoxField = value;
                this.RaisePropertyChanged("strPOBox");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string strDepStreet
        {
            get
            {
                return this.strDepStreetField;
            }
            set
            {
                this.strDepStreetField = value;
                this.RaisePropertyChanged("strDepStreet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string strStreet
        {
            get
            {
                return this.strStreetField;
            }
            set
            {
                this.strStreetField = value;
                this.RaisePropertyChanged("strStreet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string strDoubleDependantLocality
        {
            get
            {
                return this.strDoubleDependantLocalityField;
            }
            set
            {
                this.strDoubleDependantLocalityField = value;
                this.RaisePropertyChanged("strDoubleDependantLocality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string strDependantLocality
        {
            get
            {
                return this.strDependantLocalityField;
            }
            set
            {
                this.strDependantLocalityField = value;
                this.RaisePropertyChanged("strDependantLocality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string strTown
        {
            get
            {
                return this.strTownField;
            }
            set
            {
                this.strTownField = value;
                this.RaisePropertyChanged("strTown");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string strCounty
        {
            get
            {
                return this.strCountyField;
            }
            set
            {
                this.strCountyField = value;
                this.RaisePropertyChanged("strCounty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string strPostcode
        {
            get
            {
                return this.strPostcodeField;
            }
            set
            {
                this.strPostcodeField = value;
                this.RaisePropertyChanged("strPostcode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string strDPS
        {
            get
            {
                return this.strDPSField;
            }
            set
            {
                this.strDPSField = value;
                this.RaisePropertyChanged("strDPS");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string strMailsort
        {
            get
            {
                return this.strMailsortField;
            }
            set
            {
                this.strMailsortField = value;
                this.RaisePropertyChanged("strMailsort");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string strPostcodeType
        {
            get
            {
                return this.strPostcodeTypeField;
            }
            set
            {
                this.strPostcodeTypeField = value;
                this.RaisePropertyChanged("strPostcodeType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string strHouseholdCount
        {
            get
            {
                return this.strHouseholdCountField;
            }
            set
            {
                this.strHouseholdCountField = value;
                this.RaisePropertyChanged("strHouseholdCount");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string strAuthority
        {
            get
            {
                return this.strAuthorityField;
            }
            set
            {
                this.strAuthorityField = value;
                this.RaisePropertyChanged("strAuthority");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string strConstituency
        {
            get
            {
                return this.strConstituencyField;
            }
            set
            {
                this.strConstituencyField = value;
                this.RaisePropertyChanged("strConstituency");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string strTVRegion
        {
            get
            {
                return this.strTVRegionField;
            }
            set
            {
                this.strTVRegionField = value;
                this.RaisePropertyChanged("strTVRegion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string strGridEast
        {
            get
            {
                return this.strGridEastField;
            }
            set
            {
                this.strGridEastField = value;
                this.RaisePropertyChanged("strGridEast");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string strGridNorth
        {
            get
            {
                return this.strGridNorthField;
            }
            set
            {
                this.strGridNorthField = value;
                this.RaisePropertyChanged("strGridNorth");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string strLatitude
        {
            get
            {
                return this.strLatitudeField;
            }
            set
            {
                this.strLatitudeField = value;
                this.RaisePropertyChanged("strLatitude");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string strLongitude
        {
            get
            {
                return this.strLongitudeField;
            }
            set
            {
                this.strLongitudeField = value;
                this.RaisePropertyChanged("strLongitude");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string strSTDCode
        {
            get
            {
                return this.strSTDCodeField;
            }
            set
            {
                this.strSTDCodeField = value;
                this.RaisePropertyChanged("strSTDCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string strWardCode
        {
            get
            {
                return this.strWardCodeField;
            }
            set
            {
                this.strWardCodeField = value;
                this.RaisePropertyChanged("strWardCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string strWardName
        {
            get
            {
                return this.strWardNameField;
            }
            set
            {
                this.strWardNameField = value;
                this.RaisePropertyChanged("strWardName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public string strNHSCode
        {
            get
            {
                return this.strNHSCodeField;
            }
            set
            {
                this.strNHSCodeField = value;
                this.RaisePropertyChanged("strNHSCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public string strNHSName
        {
            get
            {
                return this.strNHSNameField;
            }
            set
            {
                this.strNHSNameField = value;
                this.RaisePropertyChanged("strNHSName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public string strNHSRegion
        {
            get
            {
                return this.strNHSRegionField;
            }
            set
            {
                this.strNHSRegionField = value;
                this.RaisePropertyChanged("strNHSRegion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public string strNHSRegionCode
        {
            get
            {
                return this.strNHSRegionCodeField;
            }
            set
            {
                this.strNHSRegionCodeField = value;
                this.RaisePropertyChanged("strNHSRegionCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 31)]
        public string strChanged
        {
            get
            {
                return this.strChangedField;
            }
            set
            {
                this.strChangedField = value;
                this.RaisePropertyChanged("strChanged");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public string strUDPRN
        {
            get
            {
                return this.strUDPRNField;
            }
            set
            {
                this.strUDPRNField = value;
                this.RaisePropertyChanged("strUDPRN");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.afd.co.uk/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string strOrganisationField;

        private string strPropertyField;

        private string strStreetField;

        private string strLocalityField;

        private string strTownField;

        private string strCountyField;

        private string strPostcodeField;

        private string strDPSField;

        private string strMailsortField;

        private string strPostcodeTypeField;

        private string strHouseholdCountField;

        private string strAuthorityField;

        private string strAuthorityCodeField;

        private string strConstituencyField;

        private string strTVRegionField;

        private string strGridEastField;

        private string strGridNorthField;

        private string strLatitudeField;

        private string strLongitudeField;

        private string strSTDCodeField;

        private string strWardCodeField;

        private string strWardNameField;

        private string strNHSCodeField;

        private string strNHSNameField;

        private string strNHSRegionField;

        private string strNHSRegionCodeField;

        private string strChangedField;

        private string strCensusCodeField;

        private string strAffluenceField;

        private string strLifeStageField;

        private string strAdditionalCensusInfoField;

        private string strOccupancyField;

        private string strOccupancyDescriptionField;

        private string strAddressTypeField;

        private string strAddressTypeDescriptionField;

        private string strPCTCodeField;

        private string strPCTNameField;

        private string strEERCodeField;

        private string strEERNameField;

        private string strUrbanRuralCodeField;

        private string strUrbanRuralNameField;

        private string strLEACodeField;

        private string strLEANameField;

        private string strUDPRNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string strOrganisation
        {
            get
            {
                return this.strOrganisationField;
            }
            set
            {
                this.strOrganisationField = value;
                this.RaisePropertyChanged("strOrganisation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string strProperty
        {
            get
            {
                return this.strPropertyField;
            }
            set
            {
                this.strPropertyField = value;
                this.RaisePropertyChanged("strProperty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string strStreet
        {
            get
            {
                return this.strStreetField;
            }
            set
            {
                this.strStreetField = value;
                this.RaisePropertyChanged("strStreet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string strLocality
        {
            get
            {
                return this.strLocalityField;
            }
            set
            {
                this.strLocalityField = value;
                this.RaisePropertyChanged("strLocality");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string strTown
        {
            get
            {
                return this.strTownField;
            }
            set
            {
                this.strTownField = value;
                this.RaisePropertyChanged("strTown");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string strCounty
        {
            get
            {
                return this.strCountyField;
            }
            set
            {
                this.strCountyField = value;
                this.RaisePropertyChanged("strCounty");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string strPostcode
        {
            get
            {
                return this.strPostcodeField;
            }
            set
            {
                this.strPostcodeField = value;
                this.RaisePropertyChanged("strPostcode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string strDPS
        {
            get
            {
                return this.strDPSField;
            }
            set
            {
                this.strDPSField = value;
                this.RaisePropertyChanged("strDPS");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string strMailsort
        {
            get
            {
                return this.strMailsortField;
            }
            set
            {
                this.strMailsortField = value;
                this.RaisePropertyChanged("strMailsort");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string strPostcodeType
        {
            get
            {
                return this.strPostcodeTypeField;
            }
            set
            {
                this.strPostcodeTypeField = value;
                this.RaisePropertyChanged("strPostcodeType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string strHouseholdCount
        {
            get
            {
                return this.strHouseholdCountField;
            }
            set
            {
                this.strHouseholdCountField = value;
                this.RaisePropertyChanged("strHouseholdCount");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string strAuthority
        {
            get
            {
                return this.strAuthorityField;
            }
            set
            {
                this.strAuthorityField = value;
                this.RaisePropertyChanged("strAuthority");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string strAuthorityCode
        {
            get
            {
                return this.strAuthorityCodeField;
            }
            set
            {
                this.strAuthorityCodeField = value;
                this.RaisePropertyChanged("strAuthorityCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string strConstituency
        {
            get
            {
                return this.strConstituencyField;
            }
            set
            {
                this.strConstituencyField = value;
                this.RaisePropertyChanged("strConstituency");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string strTVRegion
        {
            get
            {
                return this.strTVRegionField;
            }
            set
            {
                this.strTVRegionField = value;
                this.RaisePropertyChanged("strTVRegion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string strGridEast
        {
            get
            {
                return this.strGridEastField;
            }
            set
            {
                this.strGridEastField = value;
                this.RaisePropertyChanged("strGridEast");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string strGridNorth
        {
            get
            {
                return this.strGridNorthField;
            }
            set
            {
                this.strGridNorthField = value;
                this.RaisePropertyChanged("strGridNorth");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string strLatitude
        {
            get
            {
                return this.strLatitudeField;
            }
            set
            {
                this.strLatitudeField = value;
                this.RaisePropertyChanged("strLatitude");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string strLongitude
        {
            get
            {
                return this.strLongitudeField;
            }
            set
            {
                this.strLongitudeField = value;
                this.RaisePropertyChanged("strLongitude");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string strSTDCode
        {
            get
            {
                return this.strSTDCodeField;
            }
            set
            {
                this.strSTDCodeField = value;
                this.RaisePropertyChanged("strSTDCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string strWardCode
        {
            get
            {
                return this.strWardCodeField;
            }
            set
            {
                this.strWardCodeField = value;
                this.RaisePropertyChanged("strWardCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string strWardName
        {
            get
            {
                return this.strWardNameField;
            }
            set
            {
                this.strWardNameField = value;
                this.RaisePropertyChanged("strWardName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string strNHSCode
        {
            get
            {
                return this.strNHSCodeField;
            }
            set
            {
                this.strNHSCodeField = value;
                this.RaisePropertyChanged("strNHSCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string strNHSName
        {
            get
            {
                return this.strNHSNameField;
            }
            set
            {
                this.strNHSNameField = value;
                this.RaisePropertyChanged("strNHSName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string strNHSRegion
        {
            get
            {
                return this.strNHSRegionField;
            }
            set
            {
                this.strNHSRegionField = value;
                this.RaisePropertyChanged("strNHSRegion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string strNHSRegionCode
        {
            get
            {
                return this.strNHSRegionCodeField;
            }
            set
            {
                this.strNHSRegionCodeField = value;
                this.RaisePropertyChanged("strNHSRegionCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string strChanged
        {
            get
            {
                return this.strChangedField;
            }
            set
            {
                this.strChangedField = value;
                this.RaisePropertyChanged("strChanged");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public string strCensusCode
        {
            get
            {
                return this.strCensusCodeField;
            }
            set
            {
                this.strCensusCodeField = value;
                this.RaisePropertyChanged("strCensusCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public string strAffluence
        {
            get
            {
                return this.strAffluenceField;
            }
            set
            {
                this.strAffluenceField = value;
                this.RaisePropertyChanged("strAffluence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public string strLifeStage
        {
            get
            {
                return this.strLifeStageField;
            }
            set
            {
                this.strLifeStageField = value;
                this.RaisePropertyChanged("strLifeStage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public string strAdditionalCensusInfo
        {
            get
            {
                return this.strAdditionalCensusInfoField;
            }
            set
            {
                this.strAdditionalCensusInfoField = value;
                this.RaisePropertyChanged("strAdditionalCensusInfo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 31)]
        public string strOccupancy
        {
            get
            {
                return this.strOccupancyField;
            }
            set
            {
                this.strOccupancyField = value;
                this.RaisePropertyChanged("strOccupancy");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public string strOccupancyDescription
        {
            get
            {
                return this.strOccupancyDescriptionField;
            }
            set
            {
                this.strOccupancyDescriptionField = value;
                this.RaisePropertyChanged("strOccupancyDescription");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public string strAddressType
        {
            get
            {
                return this.strAddressTypeField;
            }
            set
            {
                this.strAddressTypeField = value;
                this.RaisePropertyChanged("strAddressType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string strAddressTypeDescription
        {
            get
            {
                return this.strAddressTypeDescriptionField;
            }
            set
            {
                this.strAddressTypeDescriptionField = value;
                this.RaisePropertyChanged("strAddressTypeDescription");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 35)]
        public string strPCTCode
        {
            get
            {
                return this.strPCTCodeField;
            }
            set
            {
                this.strPCTCodeField = value;
                this.RaisePropertyChanged("strPCTCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string strPCTName
        {
            get
            {
                return this.strPCTNameField;
            }
            set
            {
                this.strPCTNameField = value;
                this.RaisePropertyChanged("strPCTName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 37)]
        public string strEERCode
        {
            get
            {
                return this.strEERCodeField;
            }
            set
            {
                this.strEERCodeField = value;
                this.RaisePropertyChanged("strEERCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 38)]
        public string strEERName
        {
            get
            {
                return this.strEERNameField;
            }
            set
            {
                this.strEERNameField = value;
                this.RaisePropertyChanged("strEERName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 39)]
        public string strUrbanRuralCode
        {
            get
            {
                return this.strUrbanRuralCodeField;
            }
            set
            {
                this.strUrbanRuralCodeField = value;
                this.RaisePropertyChanged("strUrbanRuralCode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 40)]
        public string strUrbanRuralName
        {
            get
            {
                return this.strUrbanRuralNameField;
            }
            set
            {
                this.strUrbanRuralNameField = value;
                this.RaisePropertyChanged("strUrbanRuralName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 41)]
        public string strLEACode
        {
            get
            {
                return this.strLEACodeField;
            }
            set
            {
                this.strLEACodeField = value;
                this.RaisePropertyChanged("strLEACode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 42)]
        public string strLEAName
        {
            get
            {
                return this.strLEANameField;
            }
            set
            {
                this.strLEANameField = value;
                this.RaisePropertyChanged("strLEAName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 43)]
        public string strUDPRN
        {
            get
            {
                return this.strUDPRNField;
            }
            set
            {
                this.strUDPRNField = value;
                this.RaisePropertyChanged("strUDPRN");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostcodeEverywhereSoapChannel : PostcodeEverywhere.PostcodeEverywhereSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostcodeEverywhereSoapClient : System.ServiceModel.ClientBase<PostcodeEverywhere.PostcodeEverywhereSoap>, PostcodeEverywhere.PostcodeEverywhereSoap
    {

        public PostcodeEverywhereSoapClient()
        {
        }

        public PostcodeEverywhereSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public PostcodeEverywhereSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PostcodeEverywhereSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PostcodeEverywhereSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public PostcodeEverywhere.AddressResultsList AddressList(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strCountyType)
        {
            return base.Channel.AddressList(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strCountyType);
        }

        public PostcodeEverywhere.Address AddressLookup(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType)
        {
            return base.Channel.AddressLookup(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strPostkey, strCountyType);
        }

        public PostcodeEverywhere.AddressRaw AddressLookupRaw(string strSerialNumber, string strPassword, string strUserID, string strPostcode, string strProperty, string strPostkey, string strCountyType)
        {
            return base.Channel.AddressLookupRaw(strSerialNumber, strPassword, strUserID, strPostcode, strProperty, strPostkey, strCountyType);
        }

        public PostcodeEverywhere.AddressResultsList AddressFastFind(string strSerialNumber, string strPassword, string strUserID, string strFastFind, string strCountyType, string strSkip, string strMaxQuantity)
        {
            return base.Channel.AddressFastFind(strSerialNumber, strPassword, strUserID, strFastFind, strCountyType, strSkip, strMaxQuantity);
        }

        public PostcodeEverywhere.AddressResultsList AddressSearch(string strSerialNumber, string strPassword, string strUserID, string strOrganisation, string strProperty, string strStreet, string strLocality, string strTown, string strPostcodeFrom, string strPostcodeTo, string strCounty, string strCountyType)
        {
            return base.Channel.AddressSearch(strSerialNumber, strPassword, strUserID, strOrganisation, strProperty, strStreet, strLocality, strTown, strPostcodeFrom, strPostcodeTo, strCounty, strCountyType);
        }

        public PostcodeEverywhere.Bank BankLookup(string strSerialNumber, string strPassword, string strUserID, string strRecord)
        {
            return base.Channel.BankLookup(strSerialNumber, strPassword, strUserID, strRecord);
        }

        public PostcodeEverywhere.BankResultsList BankFastFind(string strSerialNumber, string strPassword, string strUserID, string strFastFind)
        {
            return base.Channel.BankFastFind(strSerialNumber, strPassword, strUserID, strFastFind);
        }

        public PostcodeEverywhere.BankResultsList BankSearch(string strSerialNumber, string strPassword, string strUserID, string strsortcode, string strpostcode, string strbank, string strbranch, string strphone, string strTown, string strbankBIC, string strbranchBIC)
        {
            return base.Channel.BankSearch(strSerialNumber, strPassword, strUserID, strsortcode, strpostcode, strbank, strbranch, strphone, strTown, strbankBIC, strbranchBIC);
        }

        public PostcodeEverywhere.BankValCard BankCardValidate(string strSerialNumber, string strPassword, string strUserID, string strCardNumber, string strExpiryMonth, string strExpiryYear, string strIssuenumber)
        {
            return base.Channel.BankCardValidate(strSerialNumber, strPassword, strUserID, strCardNumber, strExpiryMonth, strExpiryYear, strIssuenumber);
        }

        public PostcodeEverywhere.BankValAccount BankAccountValidate(string strSerialNumber, string strPassword, string strUserID, string strSortcode, string strAccountNumber)
        {
            return base.Channel.BankAccountValidate(strSerialNumber, strPassword, strUserID, strSortcode, strAccountNumber);
        }
    }
}
