namespace LocationService.Business_Entities
{
    internal static class Counties
    {
        internal static readonly string[] Names =
            {
                "Angus"
                ,"Argyll and Bute"
                ,"Ayrshire"
                ,"Bedfordshire"
                ,"Berkshire"
                ,"Blaenau Gwent"
                ,"Bridgend"
                ,"Bristol"
                ,"Buckinghamshire"
                ,"Caerphilly"
                ,"Cambridgeshire"
                ,"Cardiff"
                ,"Carmarthenshire"
                ,"Ceredigion"
                ,"Cheshire"
                ,"City of Edinburgh"
                ,"Cleveland"
                ,"Conwy"
                ,"Cornwall"
                ,"County Durham"
                ,"Cumbria"
                ,"Cynon"
                ,"Denbighshire"
                ,"Derbyshire"
                ,"Devon"
                ,"Dorset"
                ,"Dumfries and Galloway"
                ,"Dundee"
                ,"Dunfermline"
                ,"East Ayrshire"
                ,"East Dunbartonshire"
                ,"East Lothian"
                ,"East Renfrewshire"
                ,"East Riding of Yorkshire"
                ,"East Sussex"
                ,"East Yorkshire"
                ,"Essex"
                ,"Falkirk"
                ,"Fife"
                ,"Flintshire"
                ,"Glasgow"
                ,"Gloucestershire"
                ,"Greater London"
                ,"Greater Manchester"
                ,"Gwent"
                ,"Gwynedd"
                ,"Hampshire"
                ,"Herefordshire"
                ,"Hertfordshire"
                ,"Highland"
                ,"Inverclyde"
                ,"Kent"
                ,"Lanarkshire"
                ,"Lancashire"
                ,"Leicestershire"
                ,"Lincolnshire"
                ,"Merseyside"
                ,"Merthyr Tydfil"
                ,"Mid Glamorgan"
                ,"Mid Lothian"
                ,"Middlesex"
                ,"Midlothian"
                ,"Monmouthshire"
                ,"Moray"
                ,"Neath Port Talbot"
                ,"Newport"
                ,"Norfolk"
                ,"North Yorkshire"
                ,"Northamptonshire"
                ,"Northumberland"
                ,"Nottinghamshire"
                ,"Oxfordshire"
                ,"Pembrokeshire"
                ,"Perth and Kinross"
                ,"Peterborough"
                ,"Port Talbot"
                ,"Powys"
                ,"Renfrewshire"
                ,"Rhondda"
                ,"Rhondda Cynon Taff"
                ,"Rutland"
                ,"Scottish Borders"
                ,"Shropshire"
                ,"Somerset"
                ,"South Glamorgan"
                ,"South Yorkshire"
                ,"Staffordshire"
                ,"Stirling"
                ,"Stirlingshire"
                ,"Suffolk"
                ,"Surrey"
                ,"Sussex"
                ,"Swansea"
                ,"Taff"
                ,"Teesside"
                ,"Torfaen"
                ,"Tyne and Wear"
                ,"Vale of Glamorgan"
                ,"Warwickshire"
                ,"West Dunbartonshire"
                ,"West Lothian"
                ,"West Midlands"
                ,"West Sussex"
                ,"West Yorkshire"
                ,"Wiltshire"
                ,"Worcestershire"
                ,"Wrexham"
            };
    }
}
